### ISSUE TITLE
docs need update for adding custom resolvers

### ISSUE THREAD

**Issue by yangguang760** [lihaoyi/mill#943]
import coursier.maven.MavenRepository

object CustomZincWorkerModule extends ZincWorkerModule {
  def repositories() = super.repositories ++ Seq(
    MavenRepository("https://oss.sonatype.org/content/repositories/releases")
  )
}

object YourBuild extends ScalaModule {
  def zincWorker = CustomZincWorkerModule
  // ... rest of your build definitions
}

super.repositories does not work, for repositories is no longer the member of ZincWorkerModule.

**Comment by lefou** [comment]
Can you be more specific. What documentation is wrong. What does you snippet show?

**Comment by yangguang760** [comment]
To add custom resolvers ,the docs tell:
```
import coursier.maven.MavenRepository

object CustomZincWorkerModule extends ZincWorkerModule {
  def repositories() = super.repositories ++ Seq(
    MavenRepository("https://oss.sonatype.org/content/repositories/releases")
  )
}

object YourBuild extends ScalaModule {
  def zincWorker = CustomZincWorkerModule
  // ... rest of your build definitions
}
```
It works on version 0.7.4.
When using version 0.8.0, console outputs:
```
build.sc:23: value repositories is not a member of mill.Module with mill.scalalib.ZincWorkerModule
) ++ super.repositories 
           ^
build.sc:20: `T.sources` definitions must have 0 parameter lists
  def repositories() =  Seq(
      ^
build.sc:19: illegal inheritance;
 self-type build.this.CustomZincWorkerModule.type does not conform to mill.scalalib.ZincWorkerModule's selftype mill.scalalib.ZincWorkerModule with mill.scalalib.CoursierModule
object CustomZincWorkerModule extends ZincWorkerModule {
                                      ^
Compilation Failed
```
