### ISSUE TITLE
Mill doesn't report compile error logs outside of -watch mode

### ISSUE THREAD

**Issue by lolgab** [lihaoyi/mill#848]
Running a Scala (~Native~ **Edit**: It happens with every kind of Scala Module) project on version `0.6.2-35-7d1144` doesn't report compile errors.
It just reports:
```zsh
~/scala/test % ./mill test.compile                                            :(
[30/30] test.compile 
1 targets failed
test.compile Compilation failed
```
The `watch` mode, however, behaves correctly.

![example gif](https://user-images.githubusercontent.com/5793054/80995855-37e41600-8e3f-11ea-9803-9406ec07db0a.gif)

**Comment by lefou** [comment]
This is _only_ for Scala Native compiles, right?

**Comment by lolgab** [comment]
I supposed it was only for Scala Native. Now I checked and it happens for every kind of Scala module: JVM, JS, Native, 2.11.12, 2.13.1 etc.

**Comment by lihaoyi** [comment]
Bisected this down to 07652a610863f0cdc90fa04bc50a78082a11cab0

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/lihaoyi/mill/commit/2df7451bf3f3a8e3badc1378f5c253295f6f1ab8
