### ISSUE TITLE
Bloop/install fails with NoClassDefFoundError

### ISSUE THREAD

**Issue by krotton** [lihaoyi/mill#751]
Attempting to run `mill.contrib.Bloop/install` on a project now always fails with:

```
java.lang.NoClassDefFoundError: io/circe/RootEncoder
        at mill.contrib.bloop.BloopImpl$BloopOps$bloop$.$anonfun$config$3(BloopImpl.scala:81)
```

This happens after dependencies are resolved and downloaded, both on a bigger project of mine and a fresh one (example `build.sc` below):

```scala
import mill._, scalalib._

import $ivy.`com.lihaoyi::mill-contrib-bloop:$MILL_VERSION`

object myproject extends ScalaModule {
  def scalaVersion = "2.12.10"
}
```

Selected `scalaVersion` does not seem to affect anything, which is expected, because it's a buildscript's dependency that causes trouble, not a module's one.

**Comment by ryneflood** [comment]
Same is happening to me as well. Everything was working fine earlier today, but upgraded some packages and ever since this has been broken.

Was working earlier with v0.5.2, not working with updated v0.5.4. Tried explicitly setting different versions of Mill in `.mill-version` but to no avail

```
▶ mill mill.contrib.Bloop/install
java.lang.NoClassDefFoundError: io/circe/RootEncoder
        at mill.contrib.bloop.BloopImpl$BloopOps$bloop$.$anonfun$config$3(BloopImpl.scala:81)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
        at mill.moduledefs.Cacher.cachedTarget(Cacher.scala:12)
        at mill.moduledefs.Cacher.cachedTarget$(Cacher.scala:10)
        at mill.define.Module.cachedTarget(Module.scala:18)
        at mill.contrib.bloop.BloopImpl$BloopOps$bloop$.config(BloopImpl.scala:81)
        at mill.contrib.bloop.BloopImpl$BloopOps$bloop$.$anonfun$writeConfig$1(BloopImpl.scala:86)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
        at mill.moduledefs.Cacher.cachedTarget(Cacher.scala:12)
        at mill.moduledefs.Cacher.cachedTarget$(Cacher.scala:10)
        at mill.define.Module.cachedTarget(Module.scala:18)
        at mill.contrib.bloop.BloopImpl$BloopOps$bloop$.writeConfig(BloopImpl.scala:83)
        at mill.contrib.bloop.BloopImpl.$anonfun$install$1(BloopImpl.scala:31)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.immutable.List.map(List.scala:298)
        at mill.define.Task$.traverse(Task.scala:320)
        at mill.contrib.bloop.BloopImpl.install(BloopImpl.scala:31)
        at mill.contrib.bloop.BloopImpl.$anonfun$millDiscover$2(BloopImpl.scala:412)
        at mill.util.Router$EntryPoint.invoke(Router.scala:151)
        at mill.util.Scripts$.runMainMethod(Scripts.scala:194)
        at mill.main.Resolve$.$anonfun$invokeCommand$5(Resolve.scala:330)
        at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:742)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:741)
        at mill.main.Resolve$.$anonfun$invokeCommand$3(Resolve.scala:325)
        at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:773)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
        at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:772)
        at mill.main.Resolve$.invokeCommand(Resolve.scala:323)
        at mill.main.ResolveTasks$.endResolveLabel(Resolve.scala:206)
        at mill.main.Resolve.resolve(Resolve.scala:376)
        at mill.main.RunScript$.$anonfun$resolveTasks$4(RunScript.scala:150)
        at scala.util.Either.map(Either.scala:353)
        at mill.main.RunScript$.$anonfun$resolveTasks$3(RunScript.scala:136)
        at scala.collection.immutable.List.map(List.scala:286)
        at mill.main.RunScript$.$anonfun$resolveTasks$2(RunScript.scala:135)
        at scala.util.Either.flatMap(Either.scala:341)
        at mill.main.RunScript$.resolveTasks(RunScript.scala:132)
        at mill.main.RunScript$.evaluateTasks(RunScript.scala:193)
        at mill.main.RunScript$.$anonfun$runScript$4(RunScript.scala:67)
        at ammonite.util.Res$Success.flatMap(Res.scala:62)
        at mill.main.RunScript$.runScript(RunScript.scala:66)
        at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:91)
        at mill.main.MainRunner.watchLoop2(MainRunner.scala:57)
        at mill.main.MainRunner.runScript(MainRunner.scala:71)
        at mill.MillMain$.main0(MillMain.scala:190)
        at mill.main.MillServerMain$.main0(MillServerMain.scala:67)
        at mill.main.Server.$anonfun$handleRun$1(MillServerMain.scala:154)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.circe.RootEncoder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:241)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 52 more
```

`build.sc:`
```
import mill._, scalalib._, scalafmt._
import $ivy.`com.lihaoyi::mill-contrib-bloop:$MILL_VERSION`

object dookie extends ScalaModule with ScalafmtModule {
  def scalaVersion = "2.13.1"

  object version {
    val cats       = "2.0.0"
    val circe      = "0.12.3"
    val circeYaml  = "0.12.0"
    val doobie     = "0.8.6"
    val http4s     = "0.21.0-M6"
    val pureconfig = "0.12.1"
    val sttp       = "2.0.0-RC5"
    val zio        = "1.0.0-RC17"
    val zioMacros  = "0.6.0"
    val zioCats    = "2.0.0.0-RC10"
    val logback    = "1.3.0-alpha5"
  }

  def scalacOptions = Seq(
   "-deprecation",                  // Emit warning and location for usages of deprecated APIs.
   "-explaintypes",                 // Explain type errors in more detail.
   "-feature",                      // Emit warning and location for usages of features that should be imported explicitly.
   "-language:existentials",        // Existential types (besides wildcard types) can be written and inferred
   "-language:experimental.macros", // Allow macro definition (besides implementation and application)
    "-language:higherKinds",         // Allow higher-kinded types
   "-language:implicitConversions", // Allow definition of implicit functions called views
   "-unchecked",                    // Enable additional warnings where generated code depends on assumptions.
   "-Xcheckinit",                   // Wrap field accessors to throw an exception on uninitialized access.
   // "-Xfatal-warnings",              // Fail the compilation if there are any warnings.
   "-Xlint:adapted-args",           // Warn if an argument list is modified to match the receiver.
   "-Xlint:constant",               // Evaluation of a constant arithmetic expression results in an error.
   "-Xlint:delayedinit-select",     // Selecting member of DelayedInit.
   "-Xlint:doc-detached",           // A Scaladoc comment appears to be detached from its element.
   "-Xlint:inaccessible",           // Warn about inaccessible types in method signatures.
   "-Xlint:infer-any",              // Warn when a type argument is inferred to be `Any`.
   "-Xlint:missing-interpolator",   // A string literal appears to be missing an interpolator id.
   "-Xlint:nullary-override",       // Warn when non-nullary `def f()' overrides nullary `def f'.
   "-Xlint:nullary-unit",           // Warn when nullary methods return Unit.
   "-Xlint:option-implicit",        // Option.apply used implicit view.
   "-Xlint:package-object-classes", // Class or object defined in package object.
   "-Xlint:poly-implicit-overload", // Parameterized overloaded implicit methods are not visible as view bounds.
   "-Xlint:private-shadow",         // A private field (or class parameter) shadows a superclass field.
   "-Xlint:stars-align",            // Pattern sequence wildcard must align with sequence component.
   "-Xlint:type-parameter-shadow",  // A local type parameter shadows a type already in scope.
   "-Ywarn-dead-code",              // Warn when dead code is identified.
   "-Ywarn-extra-implicit",         // Warn when more than one implicit parameter section is defined.
   "-Ywarn-numeric-widen",          // Warn when numerics are widened.
   "-Ywarn-unused:implicits",       // Warn if an implicit parameter is unused.
   "-Ywarn-unused:imports",         // Warn if an import selector is not referenced.
   "-Ywarn-unused:locals",          // Warn if a local definition is unused.
   "-Ywarn-unused:params",          // Warn if a value parameter is unused.
   "-Ywarn-unused:patvars",         // Warn if a variable bound in a pattern is unused.
   "-Ywarn-unused:privates",        // Warn if a private member is unused.
   "-Ywarn-value-discard",          // Warn when non-Unit expression results are unused.
   "-Ybackend-parallelism", "16",      // Enable paralellisation — change to desired number!
   "-Ycache-plugin-class-loader:last-modified", // Enables caching of classloaders for compiler plugins
   "-Ycache-macro-class-loader:last-modified",   // and macro definitions. This can lead to performance improvements.
   "-Ymacro-annotations"
  )

  def ivyDeps = Agg(
    ivy"dev.zio::zio:${version.zio}",
    ivy"dev.zio::zio-macros-core:${version.zioMacros}",
    ivy"dev.zio::zio-macros-test:${version.zioMacros}",
    ivy"dev.zio::zio-interop-cats:${version.zioCats}",
    ivy"org.typelevel::cats-effect:${version.cats}",
    ivy"org.http4s::http4s-dsl:${version.http4s}",
    ivy"org.http4s::http4s-blaze-server:${version.http4s}",
    ivy"org.http4s::http4s-blaze-client:${version.http4s}",
    ivy"org.http4s::http4s-circe:${version.http4s}",
    ivy"org.tpolecat::doobie-core:${version.doobie}",
    ivy"org.tpolecat::doobie-hikari:${version.doobie}",
    ivy"org.tpolecat::doobie-postgres:${version.doobie}",
    ivy"io.circe::circe-core:${version.circe}",
    ivy"io.circe::circe-generic:${version.circe}",
    ivy"io.circe::circe-parser:${version.circe}",
    ivy"com.softwaremill.sttp.client::core:${version.sttp}",
    ivy"com.softwaremill.sttp.client::async-http-client-backend-zio:${version.sttp}",
    ivy"com.softwaremill.sttp.client::circe:${version.sttp}",
    ivy"com.github.pureconfig::pureconfig:${version.pureconfig}",
    ivy"ch.qos.logback:logback-classic:${version.logback}",
    ivy"ch.qos.logback:logback-core:${version.logback}",
  )

  object test extends Tests {
    override def ivyDeps = Agg(
      ivy"dev.zio::zio-test:${version.zio}",
      ivy"dev.zio::zio-test-sbt:${version.zio}",
      ivy"org.tpolecat::doobie-h2:${version.doobie}",
    )

    def testOne(args: String*) = T.command {
      super.runMain("org.scalatest.run", args: _*)
    }

    def testFrameworks =
      Seq("zio.test.sbt.ZTestFramework")
  }
}
```

**Comment by krotton** [comment]
I have a fix almost ready, I'll make a PR today.

**Comment by agateriver** [comment]
Same problem confirmed.

**Comment by krotton** [comment]
Until this gets merged, I can publish the fixed version of the module to GitHub packages. I'll let you know when it's done.

**Comment by krotton** [comment]
I've published the package to https://github.com/scanye/mill/packages, but I'm afraid GitHub Packages currently require authorization even for fetching from public repositories.

**Comment by krotton** [comment]
OK, I guess this is fixed now as of #756. Closing.
